steps:
  - label: ":lint-roller: Lint"
    key: "lint"
    command: .buildkite/scripts/lint.sh
    timeout_in_minutes: 10
    agents:
      queue: "build"

  - label: ":rust: Build & Unit Tests"
    key: "build"
    command: .buildkite/scripts/build.sh
    timeout_in_minutes: 15
    agents:
      queue: "build"

  - label: ":fire: Integration Tests"
    key: "integration"
    depends_on: "build"
    command: .buildkite/scripts/integration.sh
    timeout_in_minutes: 20
    agents:
      queue: "integration"
    artifact_paths:
      - "artifacts/*"
