agents:
  queue: "clawpot"

steps:
  - label: ":lint-roller: Lint"
    key: "lint"
    command: .buildkite/scripts/lint.sh
    timeout_in_minutes: 10

  - label: ":rust: Build & Unit Tests"
    key: "build"
    command: .buildkite/scripts/build.sh
    timeout_in_minutes: 15

  - label: ":fire: Integration Tests"
    key: "integration"
    depends_on: "build"
    command: .buildkite/scripts/integration.sh
    timeout_in_minutes: 20
    secrets:
      - CLAWPOT_ANTHROPIC_API_KEY
    artifact_paths:
      - "artifacts/*"
